# Generated by Django 4.0.4 on 2022-07-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pokemon_moves'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['name']},
        ),
    ]
